sudo: required
dist: trusty
language: node_js
node_js:
    - "6"
    - "7"
before_install: sudo apt-get update && sudo apt-get install gcc -y
before_script: npm install -g coveralls nyc
after_success: nyc report --reporter=text-lcov | coveralls
